version: '3.8'

services:

  mongo:
    image: mongo:latest
    restart: always
    container_name: mongodb
    hostname: localhost
    environment:
      MONGO_INITDB_ROOT_USERNAME: member
      MONGO_INITDB_ROOT_PASSWORD: 12345
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
      - mongo_logs:/var/log/mongodb
volumes:
  mongo_data:
  mongo_logs:
