spring:
    application:
        name: books
    datasource:
        url: ${spring.datasoruce.url}
        username: ${spring.datasoruce.username}
        password: ${spring.datasoruce.password}
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
    profiles:
        default: default
    config:
        import: "optional:configserver:http://localhost:7777"
server:
    port: 8081

eureka:
    instance-id: '${spring.application.name}:${random.value}'
    client:
        service-url:
            defaultZone: 'http://localhost:8761/eureka/'