spring:
    application:
        name: books
    datasource:
        url: ${spring.datasource.url}
        username: ${spring.datasource.username}
        password: ${spring.datasource.password}
        driverClassName: ${spring.datasource.driverClassName}
    hikari:
        maximum-pool-size: ${spring.hikari.maximum-pool-size}
        connection-timeout: ${spring.hikari.connection-timeout}
    profiles:
        default: default
    config:
        import: "optional:configserver:http://localhost:7777"
    jpa:
        hibernate:
            ddl-auto: update
            show-sql: true
server:
    port: 8081
logging:
    pattern:
        level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
    level:
        org:
            hibernate:
                SQL: DEBUG
                type:
                    descriptor:
                        sql:
                            BasicBinder: TRACE
eureka:
    instance-id: '${spring.application.name}:${random.value}'
    client:
        service-url:
            defaultZone: 'http://localhost:8761/eureka/'
