spring:
    application:
        name: members
    data:
        mongodb:
            database: ${spring.data.mongodb.database}
            host: ${spring.data.mongodb.host}
            port: ${spring.data.mongodb.port}
            username: ${spring.data.mongodb.username}
            password: ${spring.data.mongodb.password}
            authentication-database: ${spring.data.mongodb.authentication-database}
    hikari:
        maximum-pool-size: ${spring.hikari.maximum-pool-size}
        connection-timeout: ${spring.hikari.connection-timeout}
    profiles:
        default: default
    config:
        import: "optional:configserver:http://localhost:7777"
server:
    servlet:
        context-path: /members
    port: 8083
eureka:
    instance-id: '${spring.application.name}:${random.value}'
    client:
        service-url:
            defaultZone: 'http://localhost:8761/eureka/'

