spring:
    application:
        name: members
    datasource:
        url: ${spring.datasource.url}
        username: ${spring.datasource.username}
        password: ${spring.datasource.password}
        driverClassName: org.postgresql.Driver
    hikari:
        maximum-pool-size: ${spring.hikari.maximum-pool-size}
        connection-timeout: ${spring.hikari.connection-timeout}
    profiles:
        default: default
    config:
        import: "optional:configserver:http://localhost:7777"
server:
    port: 8081
eureka:
    instance-id: '${spring.application.name}:${random.value}'
    client:
        service-url:
            defaultZone: 'http://localhost:8761/eureka/'

